Use a helper for the 'fatal()' function
Unfortunately libshell's "fatal()" does not prefix messages with an "Error"
prefix. Introduce a new helper called "die()" which prepends messages with
"Fatal error".

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>

diff --git a/aiaiai-sh-functions b/aiaiai-sh-functions
--- a/aiaiai-sh-functions
+++ b/aiaiai-sh-functions
@@ -9,6 +9,13 @@
 if [ -z "${__included_aiaiai_sh_functions-}" ]; then
 __included_aiaiai_sh_functions=1
 
+# Print an error message and exit
+# Usage: die <message>
+die()
+{
+	fatal "Fatal error: $1"
+}
+
 # Print a separator line to stdout
 print_separator()
 {
@@ -31,7 +38,7 @@ program_required()
 	if ! command -v "$prg" >/dev/null 2>&1; then
 		message "Program \"$prg\" is required but not found in PATH"
 		if [ -n "$msg" ]; then
-			fatal "$msg"
+			die "$msg"
 		else
 			exit 1
 		fi
@@ -61,7 +68,7 @@ fetch_header_or_die()
 	local hdr="$1"; shift
 	local res="$(fetch_header "$hdr")"
 
-	[ -n "$res" ] || fatal "Cannot find the \"$hdr:\" header"
+	[ -n "$res" ] || die "Cannot find the \"$hdr:\" header"
 
 	eval "$var=\"\$res\""
 }
@@ -86,7 +93,7 @@ git_dir()
 	elif [ -d "$path" ]; then
 		printf "%s" "$path"
 	else
-		fatal "not a git repository: $path"
+		die "not a git repository: $path"
 	fi
 }
 
diff --git a/aiaiai-test-patchset b/aiaiai-test-patchset
--- a/aiaiai-test-patchset
+++ b/aiaiai-test-patchset
@@ -154,14 +154,14 @@ test_configuration()
 
 	if [ -n "$confdir" ]; then
 		defconfig="$confdir/$defconfig"
-		[ -f "$defconfig" ] || fatal "$defconfig is not available"
+		[ -f "$defconfig" ] || die "$defconfig is not available"
 	fi
 
 	if [ -n "$bisectability" ]; then
 		# We share the same source tree with 'aiaiai-test-bisectability', so
 		# wait for it (it could be run at the previous iteration)
 		if [ -n "$pid_bisect" ]; then
-			wait "$pid_bisect" || fatal "aiaiai-test-bisectability failed"
+			wait "$pid_bisect" || die "aiaiai-test-bisectability failed"
 			pid_bisect=
 		fi
 
@@ -325,7 +325,7 @@ while true; do
 	shift
 done
 
-[ "$#" -ge 2 ] || fatal 'Insufficient arguments'
+[ "$#" -ge 2 ] || die "Insufficient arguments"
 
 kernel_tree="$(readlink -ev -- "$1")"; shift
 defconfigs="$@"
@@ -433,9 +433,9 @@ for defconfig in $defconfigs; do
 	test_configuration "$defconfig"
 done
 
-wait "$pid_checkpatch" || fatal "checkpatch failed"
-[ -z "$keywords" ]     || wait "$pid_keywords" || fatal "aiaiai-match-keywords failed"
-[ -z "$pid_bisect" ]   || wait "$pid_bisect"   || fatal "aiaiai-test-bisectability failed"
+wait "$pid_checkpatch" || die "checkpatch failed"
+[ -z "$keywords" ]     || wait "$pid_keywords" || die "aiaiai-match-keywords failed"
+[ -z "$pid_bisect" ]   || wait "$pid_bisect"   || die "aiaiai-test-bisectability failed"
 
 # Print the results
 
